//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZingMp3.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZingMp3.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string SplashScreen_LoadingTextBlock_Text {
            get {
                return ResourceManager.GetString("SplashScreen_LoadingTextBlock_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Network.
        /// </summary>
        public static string SplashScreen_OnNavigatedTo_No_Network {
            get {
                return ResourceManager.GetString("SplashScreen_OnNavigatedTo_No_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Internet connection detected. Tap buttons below to switch on 3G/Wifi to use app. Tap Back to quit app.
        /// </summary>
        public static string SplashScreen_OnNavigatedTo_No_network_details {
            get {
                return ResourceManager.GetString("SplashScreen_OnNavigatedTo_No_network_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Mode.
        /// </summary>
        public static string SplashScreen_OnNavigatedTo_Offline_Mode {
            get {
                return ResourceManager.GetString("SplashScreen_OnNavigatedTo_Offline_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open app in offline mode?.
        /// </summary>
        public static string SplashScreen_OnNavigatedTo_OfflineModeQuestion {
            get {
                return ResourceManager.GetString("SplashScreen_OnNavigatedTo_OfflineModeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  added to playlist.
        /// </summary>
        public static string SplashScreen_playlist_CollectionChanged_added_to_playlist {
            get {
                return ResourceManager.GetString("SplashScreen_playlist_CollectionChanged_added_to_playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Karaoke Online for Windows Phone] - User feedback.
        /// </summary>
        public static string SplashScreen_SetupUI__EmailHeader {
            get {
                return ResourceManager.GetString("SplashScreen_SetupUI__EmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        ///I want to tell you about .
        /// </summary>
        public static string SplashScreen_SetupUI_EmailBody {
            get {
                return ResourceManager.GetString("SplashScreen_SetupUI_EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are willing to hear from you.
        /// </summary>
        public static string SplashScreen_SetupUI_Feedback {
            get {
                return ResourceManager.GetString("SplashScreen_SetupUI_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something annoying? Tell us and it will be in the next update.
        /// </summary>
        public static string SplashScreen_SetupUI_FeedbackDetails {
            get {
                return ResourceManager.GetString("SplashScreen_SetupUI_FeedbackDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send us a feed back later in &apos;Rate and Review&apos; menu in Application Bar .
        /// </summary>
        public static string SplashScreen_SetupUI_FeedbackRemind {
            get {
                return ResourceManager.GetString("SplashScreen_SetupUI_FeedbackRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great news.
        /// </summary>
        public static string SplashScreen_SetupUI_Great_news {
            get {
                return ResourceManager.GetString("SplashScreen_SetupUI_Great_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available. Latest version: .
        /// </summary>
        public static string SplashScreen_SetupUI_New_version {
            get {
                return ResourceManager.GetString("SplashScreen_SetupUI_New_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice to see you again.
        /// </summary>
        public static string SplashScreen_SetupUI_Rate {
            get {
                return ResourceManager.GetString("SplashScreen_SetupUI_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to rate 5 star and write an excellent review?.
        /// </summary>
        public static string SplashScreen_SetupUI_RateDetails {
            get {
                return ResourceManager.GetString("SplashScreen_SetupUI_RateDetails", resourceCulture);
            }
        }
    }
}
